@echo off
chcp 65001 >nul
cd /d %~dp0
echo 正在修复通知设置表...
echo 删除旧表...
mysql -uroot -proot 127_0_0_1 -e "DROP TABLE IF EXISTS la_notice_setting"
echo 创建新表...
mysql -uroot -proot 127_0_0_1 -e "CREATE TABLE la_notice_setting (id int(11) NOT NULL AUTO_INCREMENT, scene_id int(10) NOT NULL, scene_name varchar(255) NOT NULL DEFAULT '', scene_desc varchar(255) NOT NULL DEFAULT '', recipient tinyint(1) NOT NULL DEFAULT '1', type tinyint(1) NOT NULL DEFAULT '1', system_notice text, sms_notice text, oa_notice text, mnp_notice text, support char(10) NOT NULL DEFAULT '', update_time int(10) DEFAULT NULL, PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"
echo 插入数据...
mysql -uroot -proot 127_0_0_1 -e "INSERT INTO la_notice_setting VALUES (1, 101, '登录验证码', '用户手机号码登录时发送', 1, 2, '{}', '{\"status\":\"1\"}', '{}', '{}', '2', NULL), (2, 102, '绑定手机验证码', '用户绑定手机号码时发送', 1, 2, '{}', '{\"status\":\"1\"}', '{}', '{}', '2', NULL), (3, 103, '变更手机验证码', '用户变更手机号码时发送', 1, 2, '{}', '{\"status\":\"1\"}', '{}', '{}', '2', NULL), (4, 104, '找回登录密码验证码', '用户找回登录密码号码时发送', 1, 2, '{}', '{\"status\":\"1\"}', '{}', '{}', '2', NULL), (5, 105, '商家入驻验证码', '用户申请商家入驻时发送', 1, 2, '{}', '{\"status\":\"1\"}', '{}', '{}', '2', NULL)"
echo 验证...
mysql -uroot -proot 127_0_0_1 -e "SELECT COUNT(*) as count FROM la_notice_setting"
echo 完成！
pause
